// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebMVC.Data;

#nullable disable

namespace WebMVC.Data.Migrations
{
    [DbContext(typeof(BarberShopsDbContext))]
    [Migration("20261008102245_AddBarberImg")]
    partial class AddBarberImg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebMVC.Data.Models.Barber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("Barbers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 25,
                            Experience = 5,
                            FirstName = "John",
                            ImageUrl = "/images/barbers/John-Doe.png",
                            LastName = "Doe",
                            ShopId = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 25,
                            Experience = 3,
                            FirstName = "Jane",
                            ImageUrl = "/images/barbers/Jane-Smith.png",
                            LastName = "Smith",
                            ShopId = 8
                        },
                        new
                        {
                            Id = 3,
                            Age = 29,
                            Experience = 7,
                            FirstName = "Mike",
                            ImageUrl = "/images/barbers/Mike-Johnson.png",
                            LastName = "Johnson",
                            ShopId = 3
                        },
                        new
                        {
                            Id = 4,
                            Age = 28,
                            Experience = 4,
                            FirstName = "Emily",
                            ImageUrl = "/images/barbers/Emily-Davis.png",
                            LastName = "Davis",
                            ShopId = 4
                        },
                        new
                        {
                            Id = 5,
                            Age = 34,
                            Experience = 6,
                            FirstName = "David",
                            ImageUrl = "/images/barbers/David-Wilson.png",
                            LastName = "Wilson",
                            ShopId = 5
                        },
                        new
                        {
                            Id = 6,
                            Age = 22,
                            Experience = 5,
                            FirstName = "Stoyan",
                            ImageUrl = "/images/barbers/Stoyan-Stanislavov.png",
                            LastName = "Stanislavov",
                            ShopId = 1
                        },
                        new
                        {
                            Id = 7,
                            Age = 18,
                            Experience = 3,
                            FirstName = "Anna",
                            ImageUrl = "/images/barbers/Anna-Boneva.png",
                            LastName = "Boneva",
                            ShopId = 2
                        },
                        new
                        {
                            Id = 8,
                            Age = 32,
                            Experience = 7,
                            FirstName = "Ivan",
                            ImageUrl = "/images/barbers/Ivan-Petrov.png",
                            LastName = "Petrov",
                            ShopId = 3
                        },
                        new
                        {
                            Id = 9,
                            Age = 21,
                            Experience = 4,
                            FirstName = "Lyubomir",
                            ImageUrl = "/images/barbers/Lyubomir-Savov.png",
                            LastName = "Savov",
                            ShopId = 4
                        },
                        new
                        {
                            Id = 10,
                            Age = 30,
                            Experience = 3,
                            FirstName = "Denis",
                            ImageUrl = "/images/barbers/Demis-Stoilov.png",
                            LastName = "Stoilov",
                            ShopId = 7
                        });
                });

            modelBuilder.Entity("WebMVC.Data.Models.Shops", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(56)
                        .HasColumnType("nvarchar(56)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Sofia",
                            Name = "BarberShop Sofia"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Plovdiv",
                            Name = "HeadHunters Plovdiv"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Varna",
                            Name = "BarberShop Varna"
                        },
                        new
                        {
                            Id = 4,
                            Location = "Sofia",
                            Name = "BestBarbers"
                        },
                        new
                        {
                            Id = 5,
                            Location = "Plovdiv",
                            Name = "BlendHouse Plovdiv"
                        },
                        new
                        {
                            Id = 6,
                            Location = "Kalofer",
                            Name = "KaloferBarbs"
                        },
                        new
                        {
                            Id = 7,
                            Location = "Vidin",
                            Name = "BlendHouse Vidin"
                        },
                        new
                        {
                            Id = 8,
                            Location = "Smolqn",
                            Name = "HouseOFBarbers"
                        });
                });

            modelBuilder.Entity("WebMVC.Data.Models.Barber", b =>
                {
                    b.HasOne("WebMVC.Data.Models.Shops", "Shop")
                        .WithMany("Barbers")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("WebMVC.Data.Models.Shops", b =>
                {
                    b.Navigation("Barbers");
                });
#pragma warning restore 612, 618
        }
    }
}
